openapi: 3.0.1
info:
  title: test-forward-slash
  description: This api is used to connect to the test forward slash service
  version: v1.0
servers:
  - url: /
security:
  - default: []
paths:
  /*:
    get:
      parameters:
        - name: test
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: ok
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-throttling-limit:
        requestCount: -1
        unit: MINUTE
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
x-wso2-disable-security: true
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - API-Key
    - testKey
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - https://webhook.site/fd7ec3a4-1a13-4c28-8ba6-422f1bf909aa
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - https://webhook.site/fd7ec3a4-1a13-4c28-8ba6-422f1bf909aa
  type: http
x-wso2-basePath: /167688f6-08b1-4d35-b104-a70b9a3c4d67/qsbd/test-fwd-slash/v1.0
x-wso2-transports:
  - http
  - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
